# Generated by Django 2.1.3 on 2018-11-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.SmallIntegerField(choices=[(1, 'mobilize'), (2, 'guard'), (3, 'army'), (4, 'gendarmerie'), (5, 'student'), (6, 'honorable'), (7, 'committee'), (8, 'jihadist'), (9, 'market'), (10, 'Taleb'), (11, 'farmer'), (12, 'employee'), (13, 'cultural'), (14, 'un student'), (15, 'artist'), (16, 'doctor'), (17, 'nomads'), (18, 'urban'), (19, 'rural'), (20, 'soldier'), (21, 'other')])),
                ('situation', models.SmallIntegerField(choices=[(1, 'martyr'), (2, 'veteran'), (3, 'free'), (4, 'warrior'), (5, "martyrs' father"), (6, "martyrs' brother"), (7, 'deceased')])),
                ('owner_phone', models.CharField(max_length=18)),
                ('photographer_name', models.CharField(max_length=255)),
                ('shooting_date', models.DateField()),
                ('camp_name', models.CharField(max_length=255)),
                ('operational_area', models.CharField(max_length=255)),
                ('division_commander', models.CharField(max_length=255)),
                ('battalion_commander', models.CharField(max_length=255)),
                ('company_commander', models.CharField(max_length=255)),
                ('batch_commander', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('surname', models.CharField(max_length=255)),
                ('supervisor', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField()),
                ('father_name', models.CharField(max_length=255)),
                ('responsibility', models.TextField()),
                ('membership_type', models.SmallIntegerField(choices=[(1, 'mobilize'), (2, 'guard'), (3, 'army'), (4, 'gendarmerie'), (5, 'student'), (6, 'honorable'), (7, 'committee'), (8, 'jihadist'), (9, 'market'), (10, 'Taleb'), (11, 'farmer'), (12, 'employee'), (13, 'cultural'), (14, 'un student'), (15, 'artist'), (16, 'doctor'), (17, 'nomads'), (18, 'urban'), (19, 'rural'), (20, 'soldier'), (21, 'other')])),
                ('situation', models.SmallIntegerField(choices=[(1, 'martyr'), (2, 'veteran'), (3, 'free'), (4, 'warrior'), (5, "martyrs' father"), (6, "martyrs' brother"), (7, 'deceased')])),
                ('workplace', models.TextField()),
                ('phone', models.CharField(max_length=18)),
                ('type', models.SmallIntegerField(choices=[(0, 'standing'), (1, 'sitting')])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors.Report')),
            ],
            options={
                'db_table': 'soldiers',
            },
        ),
    ]
