# Generated by Django 2.1.3 on 2018-11-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='responsibility',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='workplace',
            field=models.CharField(max_length=255),
        ),
    ]
