# Generated by Django 2.1.3 on 2018-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0002_auto_20181128_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default=1, upload_to='images/soldiers', verbose_name='Image'),
        ),
    ]
