# Generated by Django 2.1.3 on 2018-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0003_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='images/soldiers', verbose_name='Image'),
        ),
    ]
