# Generated by Django 2.1.3 on 2018-12-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0004_auto_20181130_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='batch_commander',
            field=models.CharField(max_length=255, verbose_name='Batch commander'),
        ),
        migrations.AlterField(
            model_name='report',
            name='battalion_commander',
            field=models.CharField(max_length=255, verbose_name='Battalion commander'),
        ),
        migrations.AlterField(
            model_name='report',
            name='camp_name',
            field=models.CharField(max_length=255, verbose_name='Camp name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_commander',
            field=models.CharField(max_length=255, verbose_name='Company commander'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='division_commander',
            field=models.CharField(max_length=255, verbose_name='Division commander'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='images/soldiers', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='membership_type',
            field=models.SmallIntegerField(choices=[(1, 'mobilize'), (2, 'guard'), (3, 'army'), (4, 'gendarmerie'), (5, 'student'), (6, 'honorable'), (7, 'committee'), (8, 'jihadist'), (9, 'market'), (10, 'Taleb'), (11, 'farmer'), (12, 'employee'), (13, 'cultural'), (14, 'un student'), (15, 'artist'), (16, 'doctor'), (17, 'nomads'), (18, 'urban'), (19, 'rural'), (20, 'soldier'), (21, 'other')], verbose_name='Membership type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='operational_area',
            field=models.CharField(max_length=255, verbose_name='Operational area'),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner_phone',
            field=models.CharField(max_length=18, verbose_name='Own phone'),
        ),
        migrations.AlterField(
            model_name='report',
            name='photographer_name',
            field=models.CharField(max_length=255, verbose_name='Photographer name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='shooting_date',
            field=models.DateField(verbose_name='Shooting date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='situation',
            field=models.SmallIntegerField(choices=[(1, 'martyr'), (2, 'veteran'), (3, 'free'), (4, 'warrior'), (5, "martyrs' father"), (6, "martyrs' brother"), (7, 'deceased')], verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'فعال')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='supervisor',
            field=models.CharField(max_length=255, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='father_name',
            field=models.CharField(max_length=255, verbose_name='Father name'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='membership_type',
            field=models.SmallIntegerField(choices=[(1, 'mobilize'), (2, 'guard'), (3, 'army'), (4, 'gendarmerie'), (5, 'student'), (6, 'honorable'), (7, 'committee'), (8, 'jihadist'), (9, 'market'), (10, 'Taleb'), (11, 'farmer'), (12, 'employee'), (13, 'cultural'), (14, 'un student'), (15, 'artist'), (16, 'doctor'), (17, 'nomads'), (18, 'urban'), (19, 'rural'), (20, 'soldier'), (21, 'other')], verbose_name='Membership type'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='responsibility',
            field=models.CharField(max_length=255, verbose_name='Responsibility'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='situation',
            field=models.SmallIntegerField(choices=[(1, 'martyr'), (2, 'veteran'), (3, 'free'), (4, 'warrior'), (5, "martyrs' father"), (6, "martyrs' brother"), (7, 'deceased')], verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'standing'), (1, 'sitting')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='workplace',
            field=models.CharField(max_length=255, verbose_name='Workplace'),
        ),
    ]
