# Generated by Django 2.1.3 on 2018-12-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0005_auto_20181213_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='situation',
        ),
    ]
