# Generated by Django 2.1.3 on 2018-12-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0006_auto_20181213_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photographer_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Photographer address'),
        ),
    ]
