# Generated by Django 2.1.3 on 2018-12-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0007_report_photographer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photographer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photographer address'),
        ),
    ]
