# Generated by Django 2.1.3 on 2018-12-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0009_auto_20181213_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='photographer_address',
        ),
    ]
