# Generated by Django 2.1.4 on 2019-01-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0015_auto_20181214_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'گزارش', 'verbose_name_plural': 'گزارشات'},
        ),
        migrations.AlterField(
            model_name='report',
            name='batch_commander',
            field=models.CharField(max_length=255, verbose_name='فرمانده دسته'),
        ),
        migrations.AlterField(
            model_name='report',
            name='battalion_commander',
            field=models.CharField(max_length=255, verbose_name='فرمانده گردان'),
        ),
        migrations.AlterField(
            model_name='report',
            name='camp_name',
            field=models.CharField(max_length=255, verbose_name='نام اردوگاه'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_commander',
            field=models.CharField(max_length=255, verbose_name='فرمانده گروهان'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='report',
            name='division_commander',
            field=models.CharField(max_length=255, verbose_name='فرمانده لشگر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='operational_area',
            field=models.CharField(max_length=255, verbose_name='منطقه عملیات'),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner_phone',
            field=models.CharField(max_length=18, verbose_name='تلفن صاحب اثر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='photographer_address',
            field=models.CharField(max_length=255, verbose_name='مکان عکاس'),
        ),
        migrations.AlterField(
            model_name='report',
            name='photographer_name',
            field=models.CharField(max_length=255, verbose_name='نام عکاس'),
        ),
        migrations.AlterField(
            model_name='report',
            name='shooting_date',
            field=models.DateField(verbose_name='زمان عکسبرداری'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'غیرفعال'), (1, 'فعال')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='report',
            name='supervisor',
            field=models.CharField(max_length=255, verbose_name='ناظر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='father_name',
            field=models.CharField(max_length=255, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='membership_type',
            field=models.SmallIntegerField(choices=[(1, 'بسیجی'), (2, 'پاسدار'), (3, 'ارتشی'), (4, 'ژاندارمری'), (5, 'دانش آموز'), (6, 'شهربانی'), (7, 'کمیته'), (8, 'جهادگر'), (9, 'بازاری'), (10, 'طلبه'), (11, 'کشاورز'), (12, 'کارمند'), (13, 'فرهنگی'), (14, 'دانشجو'), (15, 'هنرمند'), (16, 'پزشک'), (17, 'عشایر'), (18, 'شهری'), (19, 'روستایی'), (20, 'سرباز'), (21, 'سایر')], verbose_name='نوع عضویت'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors.Report', verbose_name='گزارش'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='responsibility',
            field=models.CharField(max_length=255, verbose_name='مسئولیت'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='situation',
            field=models.SmallIntegerField(choices=[(1, 'شهید'), (2, 'جانباز'), (3, 'آزاده'), (4, 'رزمنده'), (5, 'پدر شهید'), (6, 'برادر شهید'), (7, 'فوت شده')], verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'ایستاده'), (1, 'نشسته')], verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='workplace',
            field=models.CharField(max_length=255, verbose_name='محل کار'),
        ),
    ]
